import AlterNav from './components/AlterNav'
import InitialLoader from './components/InitialLoader'
import Navigation from './components/Navigation'
import './globals.css'
// ? Anton or Russo_One
import { Anton } from 'next/font/google'
import { NavigationProvider } from './context/NavigationContext'

const anton = Anton({
  subsets: ['latin'],
  weight: ['400'],
})

export const metadata = {
  title: 'Vanja Dulikravic | Front-end Developer',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={anton.className}>
        <InitialLoader />
        <NavigationProvider>
          <Navigation />
          <AlterNav />
        </NavigationProvider>
        {children}
      </body>
    </html>
  )
}
