import InitialLoader from './components/InitialLoader'
import Navigation from './components/Navigation'
import './globals.css'
import { Anton } from 'next/font/google'

const pop = Anton({
  subsets: ['latin'],
  weight: ['400'],
})

export const metadata = {
  title: 'Vanja Dulikravic | Frontend Developer',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={pop.className}>
        <InitialLoader />
        <Navigation />
        {children}
      </body>
    </html>
  )
}
